### ISSUE TITLE
Navigation Bar: Starting point link

### ISSUE THREAD

**Issue by mkimk** [mkimk/mk_website#7]
When I click the work title, the page should move to the top of each project (the top of 'Section 1' or the top of 'Section 2'). Can we have a link for each page?

**Comment by mkimk** [comment]
https://www.w3schools.com/bootstrap/bootstrap_scrollspy.asp ?

**Comment by brianbier** [comment]
I used a library called smoothscroll. SO when you click on the title of a page it will scroll you to the top of section.
