### ISSUE TITLE
Navigation Bar: display

### ISSUE THREAD

**Issue by mkimk** [mkimk/mk_website#8]
The work title and the work description on the navigation bar are not working - Instead of the current work title 'Data', the 'Section 1' or the 'Section 2' should shown up on each project, and the work description (hidden in default) should be shown up when I click the 'Click' button.

**Comment by mkimk** [comment]
*note, the navigation bar's visibility should be changed by display property, not opacity: When the navigation bar is hidden, other items on the page (for example the 'more' button on the top) should be clickable.

**Comment by brianbier** [comment]
I've added this functionality again.
