### ISSUE TITLE
Navigation Bar: Hide it until the first slideshow is up

### ISSUE THREAD

**Issue by mkimk** [mkimk/mk_website#9]
related function: http://scrollmagic.io/examples/basic/simple_velocity.html
and I think we can work on [the navigation bar display issue](https://github.com/mkimk/mk_website/issues/8) with this plugin if it works better: http://scrollmagic.io/examples/basic/simple_pinning.html

**Comment by brianbier** [comment]
I removed scroll magic because it was to much of a plugin to use for what I wanted. I decied to use scrollama. Its better and easer to use. 
https://github.com/russellgoldenberg/scrollama
